name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt environment
        run: |
          # Set the Qt installation path with escaped backslashes
          $env:QTDIR = "C:\\Qt\\6.7.0\\msvc2019_64"

          # Add Qt binaries to PATH
          $env:Path += ";${env:QTDIR}\\bin;${env:QTDIR}\\Tools\\QtCreator\\bin"

      - name: Build the app
        run: |
          cd TicTacToe_performance
          & "${env:QTDIR}\\bin\\qmake.exe" Qt-Tic-Tac-Toe.pro
          nmake

      - name: Run the app
        run: |
          cd TicTacToe_performance/build/Desktop_Qt_6_7_2_MinGW_64_bit-Debug/release
          .\\Qt-Tic-Tac-Toe.exe

      - name: Build the tests
        run: |
          cd Qt-Tic-Tac-Toe-community/TicTacToeTest
          & "${env:QTDIR}\\bin\\qmake.exe" TicTacToeTest.pro
          nmake

      - name: Run the tests
        run: |
          cd Qt-Tic-Tac-Toe-community/TicTacToeTest/build/Desktop_Qt_6_7_2_MinGW_64_bit-Debug/debug
          .\\TicTacToeTest.exe
